### PR TITLE
Rationale fixes

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
A little while back I corrected the spelling of rationale here:
https://github.com/open-sdg/open-sdg-data-starter/pull/35

I didn't realise it was spelt the same in the translations or I probably would have left it.

But just noticed when on [Rwanda site](https://sustainabledevelopment-rwanda.github.io/sdg-site-rwanda/1-1-1/) that translation wasn't being pulled in

This may impact countries who created a platform before https://github.com/open-sdg/open-sdg-data-starter/pull/35 was merged but after the field was added

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Since that field has been there for a pretty long time, I think the backwards compatibility is a real concern. We could maybe add a duplicate translation in order to support both - but I'm wondering if the complication is worth it. Personally I'm a bit inclined to leave it misspelled for now.

**Comment by LucyGwilliamAdmin** [comment]
I was also thinking the same about leaving it but wondering what to do with open-sdg-data-starter. Should we revert the fix there?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes I guess so - we can leave the label change, but revert the key change.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Actually let me second-guess myself: If countries have used the starter repo in the time since that change was made, they'll be relying on the new spelling. So actually I'm thinking maybe we do need to duplicate the translation here (ie, have both "rational_interpretation" and "rationale_interpretation"). What do you think?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning good idea, let's add both - covers both then

**Review by brockfanning — APPROVED** [review]

**Pull request merged**
