### PR TITLE
Add 'Home' tab + sdg-translations forking query

### PR DESCRIPTION
**Pull request by Norric1Admin**
Hello @brockfanning I have a couple of questions - could you advise please?

Government usability guidelines suggest having a 'Home' tab present on all pages for clarity (below). Looking at `sdg-indicators/header.yml` I see that the hardcoding was removed earlier this year so that it points to `sdg-translations`. It's possible [get around this](https://sdg.mango-solutions.com/home-tab2/) by adding custom text in our `config.yml`, but ideally we should add a new translation instead.

I've done a mockup of a home tab at https://sdg.mango-solutions.com/home-tab/ using a [Forked release](https://github.com/Norric1Admin/sdg-translations/releases/tag/0.8.2) but when I try to link to the [translations.json](https://norric1admin.github.io/sdg-translations/translations-0.8.2.json) I'm getting the error:

```
Refused to load the image 'https://norric1admin.github.io/favicon.ico' because it violates the following Content Security Policy directive: "img-src data:".
```

- Have you come across this before? It may be a more general problem with forking `sdg-translations` (guidance of forking is [still in progress](https://open-sdg.github.io/sdg-translations/developers/)). It would be useful to know how to link to forked translations for future reference.
-  If this isn't easily resolved, are you happy for these changes to be merged into open-sdg/`master`? They are all based on existing translations for 'Home' I found in this repo.

Hope this all makes sense. Many thanks,
Chris
___

"While many users expect that a logo will be clickable, many other users will not realize that it is a link to the homepage. Therefore, include a link labeled 'Home' near the top of the page to help those users." *[Section 5.1](http://guidelines.usability.gov/guidelines/46) of guidelines.usability.gov*

### CODE REVIEW

**Comment by Norric1Admin** [comment]
P.S. If this is a real bug and not just a mistake on my part, I'm happy to start an Issue.

**Comment by brockfanning** [comment]
@Norric1Admin I don't think anything needs to be changed in this project, as we already have "Home" translated in the "general" group.

I wouldn't be opposed to changing open-sdg, though. Would it fix the problem if [this line](https://github.com/open-sdg/open-sdg/blob/master/_includes/header.html#L11) had `alt="{{ t.general.home }}"` instead of `alt="{{ t.general.sdg }} - {{ t.header.tag_line }}"`?

**Comment by brockfanning** [comment]
@Norric1Admin Sorry, think I misread your post. If it would solve the problem to simply include a "Home" link in the navigation menu, then this can already be done in _config.yml using the general.home translation we already have here.

**Comment by Norric1Admin** [comment]
Thanks for the quick response! Yes, this worked well: https://sdg.mango-solutions.com/home-tab/.

My remaining question is, how do I link to a remote translation (e.g. https://open-sdg.github.io/sdg-translations/translations-0.8.1.json) from a [forked repo](https://norric1admin.github.io/sdg-translations/translations-0.8.1.json)? It gives a 404 error.

**Pull request closed without merging**
