### PR TITLE
Adding burmese including key_words with missing translations

### PR DESCRIPTION
**Pull request by jwestw**

### CODE REVIEW

**Review by jwestw — COMMENTED** [review]
I did not mean to add scripts/check_translations.py to my commit here. These were just some tweaks to try to get it to run locally and inspect some variables. 

The other .yml files were correct though.

**Comment by LucyGwilliamAdmin** [comment]
> I did not mean to add scripts/check_translations.py to my commit here. These were just some tweaks to try to get it to run locally and inspect some variables.

Could you remove that file please as it's causing the build to fail?

Looking at the rest now though - one thing I've just realised: it didn't throw an error but link_to_data_source isn't in the metadata.yml file - see my latest comment here: https://github.com/jwestw/parse_burmese/issues/7

**Comment by jwestw** [comment]
I believe this is fixed now. Please review.

**Comment by brockfanning** [comment]
@jwestw @LucyGwilliamAdmin It is certainly the most beautiful pull-request I have seen in quite a while! ;)

However I'm not sure it makes sense to review/merge this yet. I'm seeing a few English words in there, and plenty of empty strings. I don't believe there is any rush to merge this, given that you have branch for it and can simply use that branch. But let me know if there is some reason this needs to be reviewed/merged now.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning we mainly wanted to see what terms were missing so happy for us not to merge yet

**Comment by jwestw** [comment]
@brockfanning That totally makes sense. We will point at the branch when developing the Myanmar platform.

**Comment by brockfanning** [comment]
Sounds good. It's probably already underway but another thing to keep in mind is the [goal icons](https://github.com/open-sdg/sdg-translations/tree/master/www/assets/img/goals).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks for suggestion - I've started looking into how this might be done. Been in contact with UNSD to see what they suggest

**Comment by brockfanning** [comment]
@jwestw @LucyGwilliamAdmin Now that I see how active this repo is going to be with Weblate, I'm less worried about having incomplete translations. In fact, I think we're going to have to remove that automated test. So I would be be happy to merge this as soon as the goal icons are in.

One caution about goal icons - committing English icons and then changing them to Burmese icons will cause some "Git bloat", since Git has to keep a record of past versions of files. However as long as we remember to use "Squash and merge" when we merge it, I think we'll be fine.

**Pull request merged**
