### PR TITLE
Correct incorrect short goal names

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think this is right?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I don't have any objections to the changes, but where are these corrections coming from?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Otis identified as part of the accessibility testing that screen reader was reading out slightly different things to what the goals are actually called

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I see, thanks - so this aligns them with the text on the official English goal icons. That works for me!

**Review by brockfanning — APPROVED** [review]

**Pull request merged**
